### PR TITLE
Port to Glutin

### PR DESCRIPTION
**Pull request by kvark**
Requires:
https://github.com/gfx-rs/gfx-rs/pull/682
https://github.com/gfx-rs/gfx_device_gl/pull/29
https://github.com/gfx-rs/gfx_window_glutin/pull/1

Only the performance example is left with GLFW.

### CODE REVIEW

**Comment by kvark** [comment]
btw, @tomaka - I'm getting this weird response when compiling an `#version 150 core` shader in the context created with `GlRequest::Latest`:
> 0:2(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

**Comment by tomaka** [comment]
On which platform?

**Comment by kvark** [comment]
@tomaka on Linux/X11. There is a chance I just screwed up here https://github.com/gfx-rs/gfx_window_glutin/pull/1

**Comment by kvark** [comment]
@tomaka and this is where I'm asking for the latest:
https://github.com/gfx-rs/gfx_examples/commit/70f549df71fe0c88e8f04febd2bf03eb8670613a#diff-4f71f3422ec99e0f4d2d2ba6d90704dbL388

**Comment by kvark** [comment]
@bvssvni any idea why this build is failing?

**Comment by kvark** [comment]
Figured this out, now waiting for the `gfx_window_glutin` to be updated.

**Comment by bvssvni** [comment]
@kvark Did you figure it out?

**Comment by kvark** [comment]
@bvssvni yeah, my `gfx_device_gl` dependency went horribly wrong, as simple as that. I'm locally redirecting it to local paths, and then changing briefly before committing Cargo.toml, so there is always a room for the errors there.

I need to push my latest changes to this PR before it and `gfx_examples` can be merged.

**Comment by kvark** [comment]
All green now. Merging.

**Pull request merged**
